name: audio-sharing # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.2.1' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: audio-sharing
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

slots:
  audio-sharing-svc:
    interface: dbus
    bus: session
    name: de.haeckerfelix.AudioSharing
parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  audio-sharing:
    after: [rustup]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/World/AudioSharing.git
    source-type: git
    source-tag: 0.2.1
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    meson-parameters:
      - --prefix=/snap/audio-sharing/current/usr
    build-packages:
      - libelf-dev
      - elfutils
      - libgstreamer1.0-dev
    stage-packages:
      - libgstreamer1.0-0
      - libgstrtspserver-1.0-dev
      - libfreetype-dev
      - elfutils
      - libelf1
    override-pull: |
      craftctl default
      sed -e 's|Icon=@APP_ID@|Icon=usr/share/icons/hicolor/scalable/apps/de.haeckerfelix.AudioSharing|' -i data/de.haeckerfelix.AudioSharing.desktop.in.in
    parse-info: [usr/share/metainfo/de.haeckerfelix.AudioSharing.metainfo.xml]
    organize:
      snap/audio-sharing/current/usr: usr
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - audio-sharing
      - rustup
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gnome-42-2204
      - gnome-42-2204-sdk
      - core22
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "gnome-42-2204-sdk" "core22"; do
      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
apps:
  audio-sharing:
    command: usr/bin/de.haeckerfelix.AudioSharing
    desktop: usr/share/applications/de.haeckerfelix.AudioSharing.desktop
    common-id: de.haeckerfelix.AudioSharing
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-launch
      - network
      - network-bind
      - mount-observe
      - removable-media
      - network-manager
      - audio-sharing-svc
