name: audio-sharing # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.2.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

slots:
  dbus:
    interface: dbus
    bus: session
    name: de.haeckerfelix.AudioSharing
    

parts:
  audio-sharing:
    # See 'snapcraft plugins'
    plugin: rust
    source: https://gitlab.gnome.org/World/AudioSharing.git
    source-type: git
    source-tag: 0.2.1
    rust-features:
      - extern
      - rustc-link-lib
    stage-packages:
      - libgstreamer1.0-0
      - libgstrtspserver-1.0-dev
      - libfreetype-dev
    override-prime: |
      craftctl default
      sed -e 's|Icon=de.haeckerfelix.AudioSharing|Icon=/usr/local/share/icons/hicolor/scalable/apps/de.haeckerfelix.AudioSharing|' -i usr/local/share/applications/de.haeckerfelix.AudioSharing.desktop
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - tube-converter
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gnome-42-2204
      - gnome-42-2204-sdk
      - core22
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "gnome-42-2204-sdk" "core22"; do
      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
apps:
  audio-sharing:
    command: usr/bin/audio-sharing
    desktop: usr/local/share/applications/de.haeckerfelix.AudioSharing.desktop
    common-id: de.haeckerfelix.AudioSharing
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-launch
      - network
      - network-bind 
      - mount-observe
      - removable-media
      - network-manager
